Add server delete API
metal-toolbox/conditionorc pull request #157
Opened 2023-11-30 04:04 UTC by Alva8756

Add `ServerDelete` API.

Tested with `mctl` in `sandbox`.

2023-11-30 15:18 UTC, DoctorVin requested changes
As much as I loathe the client tests, I spent a bunch of time working on them last night and they should both build and test cleanly. Moreover, the client tests should also run on a simple invocation of `go test` now (instead of being gated by a `testtools` build tag.

You should add a test for this new API there.

2023-12-01 07:04 UTC, Alva8756 commented
> As much as I loathe the client tests, I spent a bunch of time working on them last night and they should both build and test cleanly. Moreover, the client tests should also run on a simple invocation of `go test` now (instead of being gated by a `testtools` build tag.
> 
> You should add a test for this new API there.

Thanks for helping make the `client_test.go` work again! I added some tests for `serverEnroll` and `serverDelete`. PTAL when you have time. Thanks!

2023-12-01 17:29 UTC, DoctorVin requested changes
Some minor changes in the tests, please.

2023-12-01 18:12 UTC, Alva8756 commented on pkg/api/v1/client/client_test.go
> +		server.EnableServerEnroll(true),
Nice catch! Here is the link for the ticket: https://packet.atlassian.net/browse/FS-1066

2023-12-01 18:35 UTC, DoctorVin approved these changes
:shipit:

2023-12-01 18:35 UTC, DoctorVin commented on pkg/api/v1/types/types.go
> +func (asp *AddServerParams) MustJSON() []byte {
🚀

2023-12-01 18:36 UTC, merged