Switch to testify/mock and move away from go.hollow.sh/toolbox/events
metal-toolbox/conditionorc pull request #217
Opened 2024-07-01 14:25 UTC by joelrebel

#### What does this PR do

- Switches imports to `github.com/metal-toolbox/events` from `go.hollow.sh/toolbox/events`
- Changes mocks to be generated by Mockery which is in use by rivets and (imo) is nicer to work with.
- Updates all tests to use testify/mock instead of gomock.

2024-07-01 16:26 UTC, ofaurax approved these changes

2024-07-01 16:47 UTC, DoctorVin requested changes

2024-07-01 16:47 UTC, DoctorVin commented on pkg/api/v1/client/client_auth_test.go
>  	ctrl := gomock.NewController(t)
We shouldn't need this anymore?

2024-07-02 07:36 UTC, joelrebel commented on pkg/api/v1/client/client_auth_test.go
>  	ctrl := gomock.NewController(t)
nice catch, thanks, fixed

2024-07-02 11:42 UTC, DoctorVin reviewed
I don’t understand the inconsistency in asserting expectations on the mock?

2024-07-02 11:42 UTC, DoctorVin commented on pkg/api/v1/routes/handlers_test.go
> +			// Assert all expectations
Why are we doing this here and not in other tests? The GoMock ‘finisher’ asserts the mock expectations.

2024-07-02 12:24 UTC, DoctorVin approved these changes

2024-07-02 12:32 UTC, merged